### ISSUE TITLE
Test not passing in nao2

### ISSUE THREAD

**Issue by mbarbry** [cfm-mpc/pyscf#16]
@masmansouri 
@kovalp 

We must correct the tests not actually passing in nao2 branch

The tests having problems at the moments are:

FAILED TEST are:
test_0039_openmx_nao.py
test_0049_high_telec.py
test_0079_recomp_hamilt_water.py

solved:
test_0017_tddft_iter_nao.py
test_0044_h2_scf_gto_vs_nao_nao.py
test_0046_tddft_gto_h2.py
test_0053_gw_si_ref.py
test_0068_gw_f_atom.py
test_0077_chlocal_water.py
test_0081_bse_nonin_gto_be.py
test_0082_bse_gw_gto_be.py
test_0083_gw_bse_h2_ae.py
test_0085_mn_scf.py
test_0095_h2_ae_fp_rescf.py
test_0100_fireball.py
test_0160_bse_h2b_uhf_gw.py

**Comment by kovalp** [comment]
Yes, we have to correct everything. Since our aim is to merge with the upstream, I think resetting to its state could be a good start. In the branch `resetting-to-upstream-master` I started to verify tests but this is boring...

**Comment by masmansouri** [comment]
@marc, as I told you most of the failed tests in GW are stemmed from your new algorithm which is put as the default. I think it is much better to give a choice by a keyword for your new algo not as default. All of the above-mentioned tests pass in my repo with exceptions of 77,79,100.

**Comment by kovalp** [comment]
Well, we need to merge our code into the upstream too.

**Comment by kovalp** [comment]
Is your version mergeable to the upstream or it is 1000+ commits behind?

**Comment by masmansouri** [comment]
Once I merged with original pyscf and when I faced many troubles I revert it to the last commit. therefore, now it is `16 commits behind cfm-mpc:master`. You can find it [here](https://github.com/masmansouri/pyscf/tree/master)

**Comment by mbarbry** [comment]
I'm not sure that `cfm-mpc:master` is up to date with upstream.
When I tried to rebase nao branch with upstream the number of conflict were way too large. I think mainly because you reverted the changes after your rebase tentative. It probably rewrotte the history.

I will solve the issue with `rf0` to use the old version. It is easy to fix.
Then we can work on the failing tests and few other issues before to open a merge request to upstream.

**Comment by kovalp** [comment]
![image](https://user-images.githubusercontent.com/8431900/70085789-47053480-1611-11ea-8f95-97ddf04ff248.png)

This branch can be merged to the upstream. It remains only to pass all tests :-)

How about that?

**Comment by mbarbry** [comment]
Did you checkout out from `nao` or `nao2` branch when you created this branch?

From the history graph it does not look like
https://github.com/cfm-mpc/pyscf/network

If not, then your branch does not contain the latest changes from `nao`

**Comment by mbarbry** [comment]
what we should do is

    git checkout master
    git fetch upstream
    git merge upstream/master --ff-only
    git push origin master

then checkout to `nao` and rebase

    git checkout nao (or nao2)
    git rebase master

solves all the conflicts (many from `nao`, hopefully, few for `nao2`)

Once all conflicts are resolved

    git push --force-with-lease

**Comment by mbarbry** [comment]
I just updated both `master` and `dev` branches with upstream. Now we just need to do

    git checkout nao (or nao2)
    git rebase master (or dev)

solve the conflicts and

    git push --force-with-lease

Then we will be able to submit a merge request to upstream.

**Comment by mbarbry** [comment]
Dear @kovalp and @masmansouri 

I corrected the small issues with the GPU code for TDDFT and merged the pull request.
The code is now ready to be merged into upstream once the tests will pass.

Therefore, I rebased `nao2` branch with the `dev` branch from upstream. And now things are becoming harder. 

The rebase went well, with little conflict, this was a relief. The compilation went fine. But now most of the `nao` code needs to be updated in order to work with the new pyscf version. The test `test_0002_prod_basis_nao.py` is already failing with the error

    .E
    ======================================================================
    ERROR: test_gto2sv_prod_log (__main__.KnowValues)
    Test what ?
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "test_0002_prod_basis_nao.py", line 55, in test_gto2sv_prod_log
        mae,mxe,lll=prod_log.overlap_check()
      File "/media/marc/MSI-HDD/programs/pyscf/pyscf/nao/prod_log.py", line 263, in overlap_check
        return overlap_check(self, overlap_funct=overlap_ni, **kvargs)
      File "/media/marc/MSI-HDD/programs/pyscf/pyscf/nao/prod_log.py", line 36, in overlap_check
        oo_ref = overlap_funct(me,sp,R0,sp,R0,**kvargs)
      File "/media/marc/MSI-HDD/programs/pyscf/pyscf/nao/m_overlap_ni.py", line 35, in overlap_ni
        grids = build_3dgrid(me, sp1, R1, sp2, R2, **kw)
      File "/media/marc/MSI-HDD/programs/pyscf/pyscf/nao/m_ao_matelem.py", line 44, in build_3dgrid
        grids.build(atom2rcut=atom2rcut)
      File "/media/marc/MSI-HDD/programs/pyscf/pyscf/dft/gen_grid.py", line 532, in build
        self.becke_scheme)
      File "/media/marc/MSI-HDD/programs/pyscf/pyscf/dft/gen_grid.py", line 569, in gen_partition
        becke_scheme)
      File "/media/marc/MSI-HDD/programs/pyscf/pyscf/dft/gen_grid.py", line 289, in gen_partition
        f_radii_adjust = radii_adjust(mol, atomic_radii)
      File "/media/marc/MSI-HDD/programs/pyscf/pyscf/dft/radi.py", line 145, in treutler_atomic_radii_adjust
        charges = [ELEMENTS_PROTON[x] for x in mol.elements]
    AttributeError: 'nao' object has no attribute 'elements'

    ----------------------------------------------------------------------
    Ran 2 tests in 1.842s

    FAILED (errors=1)

I will try my best to solve the issues, but your help is more than welcome to have a look at this. There are probably more errors.

**Comment by mbarbry** [comment]
I solved this problem by adding the attribute `elements` to `nao` class.
See commit https://github.com/cfm-mpc/pyscf/commit/0ebb202ff18efd9489229ed9ef0151f99c0cbbc7 in branch `fix_rebase`

**Comment by kovalp** [comment]
Right. I also was adding elements in my resetting... branch

**Comment by mbarbry** [comment]
Hi!

I corrected almost all the tests in the `fix_rebase` branch. 3 tests are still failing

    test_0039_openmx_nao.py
    test_0049_high_telec.py
    test_0079_recomp_hamilt_water.py

The first one should be easy. We just need to be able to build the element list for openmx, somehow, I did not find the variable that stores the species, @kovalp do you know?

The two other tests are gonna to be harder since the results changed compared to the ref data. We will need to investigate why ...
Nevertheless, we could probably try to merge with upstream, even if these tests are failing.

Could you check that the tests are also passing for you with the branch `fix_rebase`?

**Comment by kovalp** [comment]
I hypothesise that the tests are not passing because the grid class
originating from pyscf has been changed. Because of this change, we need
the elements attribute. If results are not terribly different, then we can
redefine the references and continue developing.

To openmx: I belive the end result should be atom2symbol, right? Well, I
don't recall the internals of the openmx initialization. It is also of
little importance because we never really did anything useful with openmx.
I think the test can be omitted (skipped).

Ps. I am deeply unsatisfied with the quality of our code. Did you know that
a good style for _init_ functions would be to leave them almost empty? Do
you have ideas on how we could refactor pyscf-nao?

**Comment by mbarbry** [comment]
Hi Peter,

Ok, then I will try to open a merge request to upstream during the weekend or begin of next week.

Ja, I agree with you that the quality of the code is pretty poor, as many scientific code I'm discovering. I think we could spend sometime cleaning up, but it would be a full time job and I don't have unfortunately enough time for this. My aim here is to play a bit with the code, see if there are some technical improvements that I could do to speed it up.

**Comment by kovalp** [comment]
Right. Refactoring is a full-time job. Of course, we can do it only when
this is supported by some project.

Petr
