### ISSUE TITLE
GW Vs. GW_iter

### ISSUE THREAD

**Issue by masmansouri** [cfm-mpc/pyscf#28]
Hi @mbarbry 
at the end of `gw_iter.py`, there is a test that compares W_c obtained from gw_iter class with the one calculated in gw class. 

`gw_it = gw.get_snmw2sf_iter()`
`gw_ref = gw.get_snmw2sf()`
`print('Comparison between matrix element of W obtained from gw_iter and gw classes: ', np.allclose(gw_it, gw_ref, atol= gw.gw_iter_tol))`
I just realized this test fails in `atol` smaller than 1e-01 while it was fine in the former version with the `atol` in np.allclose as same as  `gw_iter_tol.` i.e. 1e-04.
I am working on it. Please let me know if you have any hint for this issue?

**Comment by masmansouri** [comment]
This is a problem stemming from nspin, unrestricted calculations!

**Comment by mbarbry** [comment]
Hi Massoud,

Effectively, I just run the tests, but I did not try to change the value of `atol`. What branch are you working on, `nao2`?

Also, because in some changes in scipy code, we may need to adapt the `atol` and `tol` behavior.

**Comment by masmansouri** [comment]
I am working on `nao2`. The changes that you made to calculate chi_0 in 'm_gw_chi0_noxv.py' is correct only for restricted calculation nspin=1 and fails for unrestricted calculations with nspin=2. This is why the test at the end of `gw_iter.py` for O2 molecule with spin 2 fails.

**Comment by masmansouri** [comment]
The following script could check chi_0. for RHF succeed and for UHF fails:

import sys, numpy as np 
from pyscf import gto, scf
from pyscf.nao import gw_iter
mol = gto.M(verbose=0, atom='O 0.0, 0.0, 0.0', basis='cc-pvdz', spin=0)
gto_mf = scf.UHF(mol)
gto_mf.kernel()
gw = gw_iter(mf=gto_mf, gto=mol, verbosity=3, niter_max_ev=70, kmat_algo='sm0_sum', nff_ia=3)

rf0 = gw.rf0(ww = [1j*10.0])
veff = np.ones(gw.nprod, dtype=gw.dtypeComplex)
dn_ref = np.dot(rf0[0], veff)

dn = gw.chi0_mv(veff, comega=1j*10.0)
print(abs(dn-dn_ref).sum())
print(np.allclose(dn[0],dn_ref[0],atol=1e-5))
sys.exit(1)

**Comment by masmansouri** [comment]
Hi Marc
If you agree with the function `gw_chi0_mv2` in the attached file, I could add timing and other details to commit. It seems somehow using imported div_eigenenergy, get_ab2v makes problem and just takes the last spin component.

[m_gw_chi0_noxv.py.txt](https://github.com/cfm-mpc/pyscf/files/4078724/m_gw_chi0_noxv.py.txt)

**Comment by mbarbry** [comment]
Hi Masoud,

please, create a new branch where you implement your corrections, then from this branch create a pull request to `nao2` branch, like this, Peter and I can easily review your changes.
Assuming you are in `master` branch in your local repository.

    git fetch
    git checkout nao2
    git pull
    git checkout -b your-new-branch-correction

Then implement your corrections

    git commit -m"your correction" list files modified
    git push --set-upstream origin your-new-branch-correction

Then your changes will be on the repository.
Connect to github pyscf, select your branch, and click on `New pull request`. 

Once we all agree on the changes we can merge your changes to the `nao2` branch.

The ASE documentation give a nice overview in case you create a forck and want to submit changes to upstream.
https://wiki.fysik.dtu.dk/ase/development/contribute.html#making-changes

**Comment by kovalp** [comment]
I think it is clear that Marc did wrong changes. The unittests indicate
that. Since I am not running the calculations I am not able to review. But,
I am sure Masoud is well prepared to compare new results with the old
reference results. I guess the git commands Marc mentioned could be
executed through the web interface...

**Comment by mbarbry** [comment]
The error was at least not captured by the unitests, I'm carefully running all the tests before to merge changes into `nao2`.  The test that Massoud mentions must be then added to the unitests.

**Comment by kovalp** [comment]
I see. Then this test must be added indeed.

**Comment by kovalp** [comment]
I bet there is an accumulation is left out...

**Comment by mbarbry** [comment]
Ja effectively, I see where is the issue in the loop, as you mentionned the accumulation was forgotten.
