### ISSUE TITLE
failed tests

### ISSUE THREAD

**Issue by masmansouri** [cfm-mpc/pyscf#35]
Hi @mbarbry 
It seems your recent changes do not satisfy many tests mostly by this error:
**AttributeError: /path/to/pyscf/pyscf/lib/libsparsetools.so: undefined symbol: count_nnz_spmat_denmat**

FAILED TEST are: 
test_0043_h2_vh_gto_vs_nao_nao.py
test_0044_h2_scf_gto_vs_nao_nao.py
test_0049_high_telec.py
test_0055_gw_sf_iter_polarize.py
test_0055_gw_sf_iter.py
test_0060_gw_h2_ae.py
test_0061_gw_rescf_g0w0_h2o.py
test_0061_gw_rescf_siesta_S2_triplet.py
test_0062_gw_rescf_g0w0_n2.py
test_0066_gw_al_atom.py
test_0067_gw_he_atom.py
test_0079_recomp_hamilt_water.py
test_0080_scf_gw_h2o.py
test_0081_bse_nonin_gto_be.py
test_0082_bse_gw_gto_be.py
test_0083_gw_bse_h2_ae.py
test_0085_mn_scf.py
test_0087_o2_gw.py
test_0088_beh_gw.py
test_0089_ClO_gw.py
test_0095_h2_ae_fp_rescf.py
test_0160_bse_h2b_uhf_gw.py
test_0167_cn_ugw_spin_contam.py
test_0168_cn_rohf.py
test_0169_cn_uks_b3lyp.py

**Comment by mbarbry** [comment]
That curious, I'm pretty sure to run all the test every time.
Probably I needed to reinstall from scratch to catch this error. I will have a look

**Comment by mbarbry** [comment]
Hi @masmansouri 

I recompiled everything but I could not reproduce the error.
Be sure to recompile (delete everything in your build directory) and try again.
I will try on another computer later

**Comment by masmansouri** [comment]
Hi @mark
I just reinstall pyscf from scratch. now everything related to the nao arrises Segmentation fault (core dumped). I used arch file looks like cmake.user.inc-singularity.anaconda.gnu.mkl

**Comment by mbarbry** [comment]
Hi @masmansouri 

That is weird. Please redo the compilation (delete again everything under the build directory). It could be even safer to clone again the repository (in case you have some local file interfering). Follow the following step for the compilation

    cmake -DCMAKE_BUILD_TYPE=Debug ..
    make VERBOSE=1

Then try to run the tests.

Please send me the output from cmake, make and the test run with the error message.

Also, I would like to know if you change something on your system compared to previosuly (when it was working). Maybe the linux system, gcc version, ...

**Comment by mbarbry** [comment]
I just install pyscf from scratch on a second computer. I could not reproduce the error.
Let me know if you manage to solve it, otherwise, send me the logs I asked you.

**Comment by masmansouri** [comment]
Hi @marc
I just downgraded gfortran to 7 and everything went fine. I was using gfortran-9 before.

**Comment by mbarbry** [comment]
Good that you found it. It is a known issue. https://github.com/cfm-mpc/pyscf/issues/22

I would like to investigate it, but I don't have time unfortunately.
