### ISSUE TITLE
compilation errors with gcc 9.2

### ISSUE THREAD

**Issue by mbarbry** [cfm-mpc/pyscf#8]
Dear @kovalp and @masmansouri,

I restarted to play a bit with pyscf-nao. I noticed a compilation error with recent gcc version (no problems with gcc 7.4). It is a compilation issue occurring when compiling `np_helper`, so not related to `nao`. The master branch of the original repository (from sunqm) is compiling fine. So I guess we should rebase `nao` on sunqm master branch.

Should we do this?

Best regards,
Marc

**Comment by kovalp** [comment]
Yes, we should update the branch.

**Comment by mbarbry** [comment]
It is gonna to be harder than I thought. I tried to rebase the branch on master, but there is a lot of conflicts. The risk to have a broken code at the end is quite large.

I see two options,

* we go through all conflicts with a standard rebase and hope for the best
* we can create a new branch, copying all the new nao code to it and analyze one by one the differences in the files of the standard pyscf code, if the number of modified files in the standard pyscf code is not too large, this option maybe the easiest

**Comment by mbarbry** [comment]
I opened a pull request to be able to analyze more in details the changes. They affect more than 900 files ...

**Comment by kovalp** [comment]
We need to merge from upstream and resolve all conflicts. It needs to be
done manually. I am aware of this, but I am not sure I can do this.
Ultimately, we should pull request to development branch of the upstream
repo.

**Comment by kovalp** [comment]
I think you can start by merging. There are so many changes only because we
did not merge for more than one year. I think there will be only a couple
of conflicts which require some rewriting on our side.

**Comment by mbarbry** [comment]
I tried to merge from upstream, but the number of conflicts is just crazy, and there are more than 260 commits to resolved. Fhurthermore, many files that are not from the nao directory leads to a conflict, and I don't understand why. There is even a conflict in the README ...

You can have a look at the pull request I opened.

It is why I think it may be easier to open a new branch, copy the nao code there, and start clean.

**Comment by mbarbry** [comment]
What I tried for the moment,

* I updated our master with the one of the parent repo
* I checkout nao and start to rebase, but I gave up, it was too complex

In code this gives

1. update master with upstream

    git checkout master
    git fetch upstream
    git merge upstream/master --ff-only
    git push origin master

2. rebase nao

    git checkout nao
    git rebase master

Then it starts to be crazy, with many conflicts

**Comment by kovalp** [comment]
I am sorry to hear that. I am afraid if I start looking at this, it will
take a week because I will have to improve many things.

Peter

**Comment by masmansouri** [comment]
Once I tried to merge nao to master which is more than thousand commits ahead. After merging it raised a few conflicts. I resolved them manually. So far was OK. But later, by running tests in nao branch, it resulted in many errors. As far as I remember, errors mostly had stemmed from scf class of pyscf original. I spent times to find the issue, they had defined another class for HF which had sever conflicts with our nao/scf class, rescf in particular. After few unsuccessful attempts, I finally gave up and I reverted to the former commit as you can find in got log.

**Comment by mbarbry** [comment]
ok, I guess this revert to the former commit is the origin to all these conflict ...

**Comment by mbarbry** [comment]
I opened a new branch, 'nao2'. I copied there the code from the original nao branch after having updated the rest of the pyscf code. Few tests are failings, I will try to correct them.

I think it will be easier to go through this new branch than tried to rebase the old one.

# failing tests

test_0036_cube_nao.py
test_0043_h2_vh_gto_vs_nao_nao.py
test_0044_h2_scf_gto_vs_nao_nao.py
test_0049_high_telec.py
test_0068_gw_f_atom.py
test_0070_tddft_upkc.py   # this cqn be solved easily
test_0077_chlocal_water.py
test_0079_recomp_hamilt_water.py
test_0085_mn_scf.py
test_0095_h2_ae_fp_rescf.py
test_0100_fireball.py

**Comment by kovalp** [comment]
Wau! I am glad you can do this. We at simune maybe will get intetested in
gw and stuff in a couple of years. But Masoud should be interested right
now...

**Comment by mbarbry** [comment]
Ja I would like to start to play again a bit with the code.
I corrected almost all the bugs, there are two left, but they are not coding error, there is issue in the results of the simulations. Thus it will be harder to solve. Maybe @masmansouri you could have a look if you have some time?

It is tests

*  test_0049_high_telec.py
*  test_0079_recomp_hamilt_water.py

**Comment by masmansouri** [comment]
OK, I will do.

**Comment by kovalp** [comment]
These are from tddft and gw correspondingly.
